/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Design System Colors
        'surface': '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'on-surface': '#111c2d',
        'on-surface-variant': '#3e4943',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'outline': '#6e7a73',
        'outline-variant': '#bdc9c1',
        'surface-tint': '#006c4e',
        'primary': '#005d42',
        'on-primary': '#ffffff',
        'primary-container': '#047857',
        'on-primary-container': '#9ffdd3',
        'inverse-primary': '#7bd8b1',
        'secondary': '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#82f5c1',
        'on-secondary-container': '#00714e',
        'tertiary': '#005e34',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#007945',
        'on-tertiary-container': '#98ffbc',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#97f5cc',
        'primary-fixed-dim': '#7bd8b1',
        'on-primary-fixed': '#002115',
        'on-primary-fixed-variant': '#00513a',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        'tertiary-fixed': '#8ff8b4',
        'tertiary-fixed-dim': '#73db9a',
        'on-tertiary-fixed': '#00210f',
        'on-tertiary-fixed-variant': '#00522d',
        'background': '#f9f9ff',
        'on-background': '#111c2d',
        'surface-variant': '#d8e3fb',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'display-lg-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'margin-tablet': '2rem',
        'space-lg': '1.5rem',
        'space-xs': '0.5rem',
        'gutter-tablet': '1.5rem',
        'gutter-desktop': '1.5rem',
        'space-md': '1rem',
        'gutter-mobile': '1rem',
        'margin-mobile': '1rem',
        'space-2xs': '0.25rem',
        'space-sm': '0.75rem',
        'space-3xl': '4rem',
        'margin-desktop': '2.5rem',
      },
    },
  },
  plugins: [],
}